services:
#  weaviate:
#    command:
#    - --host
#    - 0.0.0.0
#    - --port
#    - '8080'
#    - --scheme
#    - http
#    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
#    ports:
#    - "8080:8080"
#    - "50051:50051"
#    volumes:
#    - weaviate_data:/var/lib/weaviate
#    restart: on-failure:0
#    environment:
#      CLIP_INFERENCE_API: 'http://multi2vec-clip:8080'
#      QUERY_DEFAULTS_LIMIT: 25
#      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
#      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
#      DEFAULT_VECTORIZER_MODULE: 'multi2vec-clip'
#      ENABLE_MODULES: 'multi2vec-clip'
#      CLUSTER_HOSTNAME: 'node1'
#      AUTOSCHEMA_ENABLED: 'false'
#  multi2vec-clip:
#    image: cr.weaviate.io/semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
#    environment:
#      ENABLE_CUDA: '0'
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.1
    command: |
      redpanda start
      --smp 1
      --overprovisioned
      --node-id 0
      --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      --rpc-addr redpanda:33145
      --advertise-rpc-addr redpanda:33145
      --mode dev-container
      --set auto_create_topics_enabled=true
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
  console:
    image: docker.redpanda.com/redpandadata/console:v2.5.2
    entrypoint: /bin/sh
    command: |-
      -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    ports:
      - 8080:8080
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: >
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
  postgresdb:
    container_name: postgresdb
    build:
      context: "./Demo PostgreSQL Database"
      dockerfile: dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  postgresql_admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgresdb
  postgresql_cdc:
    volumes:
      - /dev/null:/app/.env
    build:
      context: "./Postgres CDC"
      dockerfile: dockerfile
    restart: always
    environment:
      output: postgres-cdc-data
      PG_HOST: postgresdb
      PG_PORT: 5432
      PG_USER: root
      PG_DATABASE: test_db
      PG_SCHEMA: public
      PG_TABLE: Products
      PG_PASSWORD: root
      Quix__Broker__Address: redpanda:9092
    depends_on:
      - postgresdb
      - redpanda
  wv_writer:
    container_name: ingest_to_weaviate
    volumes:
      - /dev/null:/app/.env
    build:
      context: "./Ingest to Weaviate"
      dockerfile: dockerfile
    env_file:
      - "./Ingest to Weaviate/.env"
    environment:
      Quix__Broker__Address: redpanda:9092
    depends_on:
      - redpanda
#  create_embeddings:
#    container_name: create_embeddings
#    build:
#      context: "./Create Embeddings with FastEmbed"
#    environment:
#      Quix__Broker__Address: redpanda:9092
#      PG_TABLE: books
#    depends_on:
#      - redpanda
  streamlit_search:
    container_name: streamlit_search
    build:
      context: "./Streamlit Search UI"
      dockerfile: dockerfile
    env_file:
      - "./Streamlit Search UI/.env"
    environment:
      Quix__Broker__Address: redpanda:9092
    ports:
      - "8082:80"
