name: Ingest to Weaviate Images
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: transform
    required: false
  - name: qd_host
    inputType: FreeText
    description: The db host
    defaultValue: qdrant
    required: true
  - name: qd_port
    inputType: FreeText
    description: The db port
    defaultValue: 6333
    required: true
  - name: qd_collection
    inputType: FreeText
    description: The db name
    defaultValue: test_db
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
